/* THE TOKEN MODEL (v2, after the independent review of 2026-09-23).
 * Light values are the console's, as it renders them today (console-palette.json); dark values are the two sister
 * products' dark block (variable_ServiceOps / variable_Obeservops → sisters/sisters.json), matched BY JOB. Naming
 * follows Atlassian's grammar: color.text.*, color.background.*, elevation.surface.*, color.border.*, color.icon.*,
 * color.link, color.blanket, color.skeleton; component tokens (component.*) only where a part needs its own.
 * Every entry names where each side comes from. `flag` marks a call for Pranjal; "derived" means no sister value
 * exists for that job and the value was made by the sisters' own rule. */
const T = (name, group, job, light, lightFrom, dark, darkFrom, extra = {}) => ({ name, group, job, light, lightFrom, dark, darkFrom, ...extra });
const SURFACES = ['elevation.surface', 'elevation.surface.raised', 'elevation.surface.overlay'];

const semantic = [
  /* ── TEXT ─────────────────────────────────────────────────────────── */
  T('color.text', 'text', 'Reading text: names, values, titles, body.', '#1D2B3E', 'console neutral-110/150 (C-45, ink-700)', '#CAD3E2', '--page-text-color dark (both products)', { sisterLight: '#1D2A3E --page-text-color', lib: '--mdt-neutral-130 / console t.ink', on: SURFACES }),
  T('color.text.subtle', 'text', 'Secondary text: labels, supporting lines, table cells, the slate badge\'s ink.', '#516281', 'console neutral-90 (C-46, ink-600)', '#8E9FBC', '--tabs-text-color dark · --neutral-light dark · --text-color-common-secondary dark', { sisterLight: '#516381 --tabs-text-color', lib: '--mdt-neutral-90', on: SURFACES.concat(['color.background.neutral']), note: 'On the slate chip (#2B394F) the dark pair measures 4.35:1 - a hair under the 4.5 floor. The light pair is 5.42:1.' }),
  T('color.text.subtlest', 'text', 'The faint ink: placeholders, meta lines, resting tab labels, empty values.', '#8FA0BD', 'console --mdt-faint (C-112; 2.65:1 on white - his accepted exception, C-108)', '#6A7FA0', '--neutral-regular dark · --chart-closed dark · --coverage-empty-outline dark ("dimmer than neutral-light")', { sisterLight: '#7B8FA5 --secondary-text-color · placeholder rgba(43,57,79,.5)', lib: '--mdt-faint', on: SURFACES, note: 'The sisters\' dark placeholder is rgba(202,211,226,.5), which composites to #697281 over the page - the same step. A solid is used so it reads the same on every surface. Dark measures 4.67:1 on the page, 3.88 on a card, 3.55 on a menu: better than light\'s 2.65 everywhere, still under 4.5 off the page.' }),
  T('color.text.input', 'text', 'A value typed into a field: what the user filled in, not the placeholder.', '#516281', 'console neutral-90 (C-46: typed values wear the secondary ink)', '#CAD3E2', 'color.text dark - a filled value reads as content, the same ink as names in a table', { lib: '--mdt-neutral-90 on input', on: ['color.background.input', 'elevation.surface.raised'], note: 'Split from color.text.subtle so the dark typed value can match the table names (#CAD3E2) while light stays as the console paints it.' }),
  T('color.text.disabled', 'text', 'Text of a control that cannot be used.', '#8FA0BD', 'console: a disabled field keeps neutral-70 at opacity 1 (C-68)', 'rgba(255, 255, 255, 0.5)', '--button-disabled-text dark', { sisterLight: 'rgba(0,0,0,.5) --button-disabled-text', lib: 'disabled:mdt-opacity-50 (a different method)', on: ['elevation.surface', 'elevation.surface.raised', 'color.background.disabled'] }),
  T('color.text.inverse', 'text', 'Text and glyphs on a bold fill: the primary button\'s label, the destructive button\'s label, the switch\'s thumb, the checkbox\'s tick.', '#FFFFFF', 'console --mdt-primary-foreground', '#0B1628', 'storybook neutral-160 - the library Button\'s own dark label (dark:mdt-text-neutral-160); the sisters\' --primary-button-text dark #07101F is one unit off it (Pranjal 2026-09-24: the storybook is the source)', { lib: '--mdt-primary-foreground', on: ['color.background.brand.bold', 'color.background.danger.bold', 'color.background.selected.bold'] }),
  T('color.text.brand', 'text', 'The brand ink: an active tab label and its underline, the selected nav item, a settled step. Also the near-black the sidebar uses.', '#070F1D', 'console --mdt-primary / --mdt-black (C-50, C-69; C-48 "two blacks" stays his call)', '#E3E8F2', '--primary dark (both products)', { sisterLight: '#07101F ServiceOps · #111C2C ObservOps (they disagree)', lib: '--mdt-primary as ink', on: ['elevation.surface', 'elevation.surface.raised'] }),
  T('color.link', 'text', 'A link, and the interactive blue a mark reads in.', '#0262DE', 'console --mdt-blue-60 / --mdt-info / --mdt-ring (C-57)', '#008CFF', '--page-link-color dark · --severity-maintenance dark', { sisterLight: '#006DFA --page-link-color (a different blue - ours stays)', lib: '--mdt-blue-60 / --mdt-info', on: ['elevation.surface', 'elevation.surface.raised'] }),
  T('color.text.danger', 'text', 'Danger as words or a glyph: the destructive menu row, an error message, a failed count.', '#DD132B', 'console --mdt-destructive / red-60 (C-113; the library triplet renders #DB132A - one unit, C-116)', '#EC5B5B', '--severity-critical (the same in both themes) · --error-button-bg dark', { sisterLight: '#EC5B5B --severity-critical (both) · the error-outline text is #EC5B5B in light and #C84235 / #AD1111 in DARK (they disagree)', lib: '--mdt-destructive / --mdt-red-60', on: SURFACES.concat(['color.background.danger']), note: 'Dark on a menu (#1D2A3E) measures 4.28:1 - under the floor by a little; on the page 5.6:1. The sisters use this red on every ground.' }),
  T('color.text.success', 'text', 'Success as words or a glyph: the Active badge ink, a success count.', '#21823A', 'console green-80 / feedback-success-icon (C-59, C-84)', '#5ED6A8', '--detail-tag-success-text dark (ServiceOps; the tinted chip\'s ink)', { sisterLight: '#0E8A63 --detail-tag-success-text · #14B053 --severity-clear', lib: '--mdt-green-80', on: ['color.background.success', 'elevation.surface.raised'], note: 'For a solid status dot the severity ramp applies instead: clear #14B053 → #36D576 (see Status).' }),
  T('color.text.warning', 'text', 'Warning as words or a glyph: the Invited / Expiring badge ink, "3 days left".', '#9F6404', 'console orange-80 / feedback-warning-icon (C-60, C-84)', '#E3A44A', '--detail-tag-warning-text dark (ServiceOps)', { sisterLight: '#B4690E --detail-tag-warning-text', lib: '--mdt-orange-80', on: ['color.background.warning', 'elevation.surface.raised'] }),
  T('color.text.information', 'text', 'Information as words or a glyph: the information badge ink (the library\'s Badge calls the tone "info"), an info callout\'s icon.', '#0262DE', 'console blue-60 / feedback-info-icon', '#7FB2E0', '--detail-tag-info-text dark (ServiceOps)', { sisterLight: '#2E6FA8 --detail-tag-info-text', lib: '--mdt-blue-60 / --mdt-feedback-info-icon', on: ['color.background.information', 'elevation.surface.raised'] }),
  T('color.text.ai', 'text', 'The AI purple as ink: the AI badge, the AI callout icon.', '#6C2ED1', 'console purple-60 (C-62)', '#A855F7', '--chart-neon-purple dark (the only purple the sisters flip; their AI accent is a blue)', { sisterLight: '#9333EA --chart-neon-purple', lib: '--mdt-purple-60', on: ['color.background.ai', 'elevation.surface.raised'], flag: 'Weakest match, and it measures 3.99:1 on a dark card - under the floor. The sisters have no purple text role; their lightened purple for dark is --license-violet #BB9AF7 (ObservOps, 7.2:1 on the card) - the alternative. The AI gradient stops stay theme-independent, as their file keeps them (#4CB1FE / #731EFB / #F911E3, one unit off the console\'s #4DB2FE / #721DFC / #F910E2).' }),

  /* ── SURFACES (elevation) ─────────────────────────────────────────── */
  T('elevation.surface', 'surface', 'The page itself, and a drawer or dialog panel (the sisters paint those the page colour).', '#FFFFFF', 'console --mdt-background (C-49)', '#07101F', '--page-background-color dark · --modal-background-color dark · --drawer-background-color dark', { lib: '--mdt-background', note: 'In dark the sisters give a modal and a drawer the page colour and let the scrim and shadow separate them.' }),
  T('elevation.surface.sunken', 'surface', 'The canvas behind cards: the app ground, a dashboard, a terminal-like panel.', '#F7FAFC', 'console neutral-10 (C-10 "the canvas tint")', '#0B1627', '--dashboard-background dark · --utility-result-bg dark (ObservOps) · --noc-panel-bg dark', { sisterLight: '#ECF1F9 --common-main-bg · #F9FAFB --dashboard-background', lib: '--mdt-neutral-10 / --mdt-muted', note: 'Dark elevation runs the other way from light: the higher a surface sits, the lighter it is. Ladder: 07101F page → 0B1627 canvas → 172336 card → 1D2A3E overlay → 2B394F hovered → 485975 pressed.' }),
  T('elevation.surface.raised', 'surface', 'A card: the table card, a KPI card, a widget, the drawer\'s band card, a toast.', '#FFFFFF', 'console --mdt-card / --mdt-surface-raised (C-54: white on white, separated by edge and shadow)', '#172336', '--widget-background-color dark · --common-widget-bg dark · --toast-background-color dark', { lib: '--mdt-card / --mdt-surface-raised', note: 'A toast is a raised card in both themes in the sisters (white → #172336), not an inverse ground.' }),
  T('elevation.surface.overlay', 'surface', 'A menu, a popover, a select list, a date panel: things that float over the page.', '#FFFFFF', 'console --mdt-popover', '#1D2A3E', '--dropdown-background dark · --action-dropdown-backgroud dark', { lib: '--mdt-popover', note: 'In dark this is the same hex as the hairline (color.border) and the quiet fill (color.background.neutral.subtle) - faithful to the sisters, where --dropdown-background, --border-color and --tag-bg are all #1D2A3E. Inside a menu, use color.border.bold (#2B394F) for a divider and color.background.neutral (#2B394F) for a chip, or they vanish.' }),

  /* ── BACKGROUNDS ─────────────────────────────────────────────────── */
  T('color.background.neutral.subtle', 'background', 'The quiet fill: a chip or tag ground, a disabled field, an icon tile\'s ground, the neutral badge.', '#F7FAFC', 'console neutral-10 / --mdt-muted (C-49, C-83, C-86)', '#1D2A3E', '--tag-bg dark · --neutral-lighter dark · --pii-card-bg dark', { sisterLight: '#ECF1F9 --tag-bg', lib: '--mdt-muted / --mdt-neutral-10', note: 'Atlassian\'s order: "subtle" is the quieter step, "neutral" the stronger.' }),
  T('color.background.neutral', 'background', 'The stronger quiet fill: the slate badge, the segmented track, a folded panel, the bulk bar\'s ground, the progress track.', '#ECF1F9', 'console neutral-20 / --mdt-secondary (C-11, C-83 slate)', '#2B394F', '--default-tag-bg dark (ServiceOps #2B394F; ObservOps says rgba(9,157,217,.3) - they disagree) · --table-details-bg dark · --tag-bg-color dark · --progress-bar-bg dark', { sisterLight: '#E3E8F2 --default-tag-bg (ServiceOps)', lib: '--mdt-secondary / --mdt-neutral-20' }),
  T('color.background.neutral.subtle.hovered', 'background', 'Under the pointer on a menu row, a toolbar square, a ghost or outline button.', '#F7FAFC', 'console neutral-10 (ST-19: the one hover ground)', '#2B394F', '--dropdown-hover-background dark (both products)', { sisterLight: '#ECF1F9 --dropdown-hover-background / --list-menu-hover', lib: '--mdt-neutral-10 under hover:', note: 'One step up the ladder from the menu it sits on.' }),
  T('color.background.neutral.subtle.pressed', 'background', 'Held down, or the ⋯ door while its menu is open.', '#ECF1F9', 'console neutral-20 (C-73: the kebab\'s open fill)', '#485975', '--slider-tracker · --loader-primary-color dark · --pan-btn-bg dark (ObservOps)', { lib: '--mdt-neutral-20' }),
  T('color.background.neutral.bold', 'background', 'A bold neutral fill: the switch\'s off track, the slider track.', '#CAD3E2', 'console neutral-40 (K-Switch: the 36×20 track; measured rgb(202,211,226))', '#485975', '--slider-tracker (the same in both themes) · --switch-port-view-bg dark', { lib: '--mdt-neutral-40', note: 'Atlassian names the toggle-off track this way.' }),
  T('color.background.neutral.bold.hovered', 'background', 'The off track under the pointer.', '#B9C3D4', 'console: the switch mock\'s shade (K-Switch-05; not a palette step)', '#6A7FA0', 'derived: one step up the ramp from #485975 - the sisters have no switch hover', { lib: 'hover:mdt-bg-[#B9C3D4]', flag: 'Derived.' }),
  T('color.background.selected', 'background', 'A picked row, a checked option row, the selected nav item\'s ground.', '#F2F6FA', 'changed from blue-10 #F0F6FE: a neutral step between neutral-10 (#F7FAFC) and neutral-20 (#ECF1F9), so the neutral, slate and information chips all keep an edge on a picked row', 'rgba(227, 232, 242, 0.06)', '--dropdown-active-bg dark (primary as a wash), at 6% instead of 12% - at 12% it composites to the slate chip\'s #2B394F on a card and the Inactive chip vanishes', { sisterLight: 'primary 12% (= #07101F at .12)', lib: '--mdt-accent / --mdt-blue-10', note: 'Neutral family in both themes and kept light. Measured on a card: light is 1.04:1 against the neutral and slate chips (the same step neutral chips already have on white); dark is 1.16:1 against the slate chip and 1.07:1 against the hovered row. The blue picked row was the one light-theme change made on request.' }),
  T('color.background.selected.bold', 'background', 'A bold selected fill: the checked checkbox, the switch\'s on track, the chosen radio.', '#070F1D', 'console: primary (K-Switch, K-Checkbox-03)', '#CAD3E2', '--checkbox-checked-color dark (both) · --radio-btn-box-selected-bg dark is #E3E8F2 (= primary)', { lib: '--mdt-primary on controls', text: 'color.text.inverse', flag: 'The sisters fill a checked box #CAD3E2 - one step softer than the white button. Proposed: #CAD3E2 for the small controls, white for the button.' }),
  T('color.background.input', 'background', 'A field\'s ground at rest.', '#FFFFFF', 'console: fields are white (C-66; the search box renders transparent over the white page)', '#07101F', '--text-input-bg dark = page · --input-background dark (ObservOps: transparent)', { lib: '--mdt-background', flag: 'On a card (#172336) a #07101F field reads as a hole. The sisters put fields on the page. His call: page colour (strict) or transparent (ObservOps).' }),
  T('color.background.input.disabled', 'background', 'A field that cannot be used.', '#F7FAFC', 'console neutral-10 (C-68)', '#111C2C', '--input-background-disabled dark (ObservOps)', { lib: '--mdt-neutral-10' }),
  T('color.background.brand.bold', 'background', 'The primary button, a settled stepper disc.', '#070F1D', 'console --mdt-primary (C-50)', '#ECF1F9', 'storybook neutral-20 - the library Button\'s own dark fill (dark:mdt-bg-neutral-20). Pranjal 2026-09-24: "use neutral 20 from the storybook for the primary color in dark theme"; the sisters\' --primary-button-bg dark was #FFFFFF', { lib: '--mdt-primary', text: 'color.text.inverse' }),
  T('color.background.brand.bold.hovered', 'background', 'The primary button under the pointer.', '#1D2B3E', 'console: hover moves along the ramp (C-71) - neutral-110 (the library Button: hover:mdt-bg-neutral-110)', '#F6F9FC', 'storybook neutral-10 - the library Button\'s own dark hover (dark:hover:mdt-bg-neutral-10); a step lighter than the fill, as light is a step darker. Ruled 2026-09-24 with brand.bold; the sisters faded (fade(#fff, 70)) and C-71 forbids fading', { lib: '--mdt-primary-hover', text: 'color.text.inverse' }),
  T('color.background.brand.bold.pressed', 'background', 'The primary button held down.', '#384861', 'console neutral-100 (the library Button: active:mdt-bg-neutral-100)', '#CAD3E2', 'storybook neutral-40 - the library Button\'s own dark pressed step (dark:active:mdt-bg-neutral-40)', { lib: '--mdt-primary-active', text: 'color.text.inverse' }),
  T('color.background.danger.bold', 'background', 'The destructive button.', '#DD132B', 'console --mdt-destructive', '#EC5B5B', '--error-button-bg dark = severity-critical', { lib: '--mdt-destructive', text: 'color.text.inverse', flag: 'The sisters\' own dark label is their page text #CAD3E2 (--error-button-text dark), which measures 2.24:1 on this red - not followed. color.text.inverse (#07101F) measures 6.05:1; white would be 3.15.' }),
  T('color.background.danger.bold.hovered', 'background', 'The destructive button under the pointer.', '#DD132B', 'console: the destructive button has no hover fill today (Button.tsx)', '#C84235', '--error-button-hover-bg dark (ServiceOps; ObservOps says #AD1111 - they disagree)', { lib: 'Button destructive (no hover class)', text: 'color.text.inverse', flag: 'Light has no hover step today; the sisters darken. His call which red.' }),
  T('color.background.danger', 'background', 'The danger wash: under the destructive menu row, the error banner, the danger badge.', '#FCE3E6', 'console --mdt-feedback-danger-bg (C-64)', 'rgba(192, 57, 43, 0.24)', '--detail-tag-danger-bg dark (ServiceOps: "a translucent wash of its own hue")', { sisterLight: '#FDECEA --detail-tag-danger-bg · #FEF5F5 --severity-critical-lighter', lib: '--mdt-feedback-danger-bg / --mdt-red-10', note: 'Solid alternative from the severity ramp: critical-lighter #310C0C.' }),
  T('color.background.success', 'background', 'The success tint: the Active badge, the success banner.', '#DCF4E4', 'console --mdt-feedback-success-bg / green-10', 'rgba(16, 185, 129, 0.24)', '--detail-tag-success-bg dark (ServiceOps)', { sisterLight: '#E8F7F1 --detail-tag-success-bg · #D1FAE0 --severity-clear-lighter', lib: '--mdt-feedback-success-bg / --mdt-green-10', note: 'Solid alternative: clear-lighter #0D3A1F.' }),
  T('color.background.warning', 'background', 'The warning tint: the Invited / Expiring badge, the warning banner.', '#FFF3DB', 'console --mdt-feedback-warning-bg', 'rgba(180, 105, 14, 0.26)', '--detail-tag-warning-bg dark (ServiceOps)', { sisterLight: '#FEF6E7 --detail-tag-warning-bg · #FFF1B3 --severity-warning-lighter', lib: '--mdt-feedback-warning-bg', note: 'Solid alternative: warning-lighter #543308.' }),
  T('color.background.information', 'background', 'The information tint: the information badge, the info banner, the owner mark\'s circle.', '#F0F6FE', 'console --mdt-feedback-info-bg / blue-10', 'rgba(46, 111, 168, 0.26)', '--detail-tag-info-bg dark (ServiceOps)', { sisterLight: '#EAF3FB --detail-tag-info-bg · #CCE4FF --severity-maintenance-lighter', lib: '--mdt-feedback-info-bg / --mdt-blue-10', note: 'Solid alternative: maintenance-lighter #001489 - a saturated navy, too loud for a panel.' }),
  T('color.background.ai', 'background', 'The AI tint: the AI badge and callout ground.', '#F4EEFC', 'console --mdt-feedback-ai-bg / purple-10', 'rgba(168, 85, 247, 0.16)', 'derived: --chart-neon-purple dark at 16% - the sisters have no AI tint (their AI grounds collapse to #1D2A3E in dark)', { lib: '--mdt-feedback-ai-bg', flag: 'Derived, not read off a sister value.' }),
  T('color.background.inverse', 'background', 'A dark ground on a light page: the tooltip, the inverse badge.', '#1D2B3E', 'console: the tooltip and inverse badge ground (neutral-150)', 'rgba(43, 57, 79, 0.9)', '--tooltip-background-color dark (both products)', { lib: '--mdt-neutral-150', text: 'component.tooltip.text' }),
  T('color.background.disabled', 'background', 'A button that cannot be used.', '#F7FAFC', 'console neutral-10 (the library: opacity 50%)', 'rgba(43, 57, 79, 0.7)', '--button-disabled-bg dark', { lib: 'disabled:mdt-opacity-50' }),
  T('color.blanket', 'background', 'The scrim behind a drawer or a dialog.', 'rgba(0, 0, 0, 0.45)', 'console drawer mask (= the sisters\' --drawer-mask-color light; no --mdt-* token holds it)', 'rgba(0, 0, 0, 0.6)', 'derived - the sisters\' dark mask is rgba(255,255,255,.45), a WHITE veil on a dark page (--drawer-mask-color dark); ServiceOps\' own --modal-backdrop-dim (#14152680, declared once and inherited by dark) keeps a dark veil', { lib: 'Sheet/Dialog overlay', flag: 'The one place the sisters are not followed: a white veil on a dark page washes the page out. His call: black at 60% (proposed) or their white at 45%.' }),
  T('color.skeleton', 'background', 'A loading placeholder\'s bar.', '#ECF1F9', 'console neutral-20 (the loader\'s secondary)', '#2B394F', '--loader-secondary-color dark', { lib: '--mdt-neutral-20' }),
  T('color.skeleton.subtle', 'background', 'The loading placeholder\'s lighter sweep.', '#F7FAFC', 'console neutral-10 (the loader\'s primary)', '#485975', '--loader-primary-color dark', { lib: '--mdt-neutral-10' }),

  /* ── BORDERS ─────────────────────────────────────────────────────── */
  T('color.border', 'border', 'The hairline: card edges, dividers, the table\'s row lines, the band\'s rule.', '#ECF1F9', 'console --mdt-border = neutral-20 (C-51: one border grey everywhere; the table divider)', '#1D2A3E', '--border-color dark (both products) · --grid-row-border-color dark rgba(23,35,54,.7)', { sisterLight: '#E3E8F2 --border-color', lib: '--mdt-border', note: 'In dark the same hex as a menu\'s ground: a hairline inside a menu vanishes (1.00:1). Use color.border.bold there - the sisters carry the same collision.' }),
  T('color.border.bold', 'border', 'The stronger edge: an unchecked checkbox, the strong border, the stepper\'s pending ring, a divider inside a menu.', '#E3E8F2', 'console neutral-30 (C-12, C-66; K-Stepper)', '#172336', 'storybook neutral-140 (Pranjal 2026-09-24: "change the color of divider to neutral 140 in sidebar #172336 and other borders as well if they have the same color as this" - the sidebar separator reads border.bold; this token carried the same hex) - before it: --field-border-color dark · --tag-border dark (ServiceOps) · --calendar-border-color dark · --steps-neutral-lighter dark (ServiceOps)', { sisterLight: '#E3E8F2 --field-border-color', lib: '--mdt-neutral-30' }),
  T('color.border.input', 'border', 'A field\'s edge at rest (the console draws it neutral-30; the library token says neutral-40).', '#E3E8F2', 'console C-66 (the library\'s --mdt-input is #CAD3E2 - C-13)', '#172336', 'storybook neutral-140 (Pranjal 2026-09-24: "change the color of divider to neutral 140 in sidebar #172336 and other borders as well if they have the same color as this" - the sidebar separator reads border.bold; this token carried the same hex) - before it: --field-border-color dark', { lib: '--mdt-input', flag: 'Light stays as the console draws it (neutral-30); the library\'s --mdt-input still says neutral-40 - the standing disagreement.' }),
  T('color.border.input.hovered', 'border', 'A field\'s edge under the pointer.', '#070F1D', 'console: hover takes the primary edge (C-66; the search box renders it)', '#485975', '--input-border-color-hover dark (ObservOps) · --border-color-hover dark #35455E (ServiceOps)', { lib: 'hover:mdt-border-primary', flag: 'Strict mapping of "primary" would give #E3E8F2 (very bright); the sisters\' own field hover is the quieter #485975. His call.' }),
  T('color.border.focused', 'border', 'The focus ring: the field\'s focus edge and its 3px halo at 8%, the keyboard ring.', '#0262DE', 'console --mdt-ring = blue-60 (the field: primary edge + halo, C-66)', '#7186A8', '--input-border-color-focus dark (ObservOps) · --focus-color dark #204CA2 (both, for radio and tag edges)', { lib: '--mdt-ring', flag: 'Two candidates in the sisters: #7186A8 (field focus) and #204CA2 (their dark focus colour). Our light ring is blue; #204CA2 keeps it blue.' }),
  T('color.border.selected', 'border', 'The edge of a picked thing: the chosen segment, a selected card, the checked checkbox.', '#070F1D', 'console: the primary edge (K-Radio-08, K-Checkbox-03)', '#CAD3E2', '--checkbox-checked-color dark · --primary-alt dark', { lib: 'mdt-border-primary', note: 'Same paint as color.background.selected.bold - an alias by design.' }),
  T('color.border.danger', 'border', 'A field in error, the danger banner\'s edge.', '#DD132B', 'console --mdt-destructive (C-113: error borders red-60)', '#EC5B5B', '--severity-critical', { lib: '--mdt-destructive / --mdt-feedback-danger-border' }),
  T('color.border.disabled', 'border', 'The edge of a control that cannot be used.', '#E3E8F2', 'console: a disabled outline button keeps its neutral-30 edge under the library\'s opacity 50', 'rgba(72, 89, 117, 0.7)', '--button-disabled-border dark', { lib: 'disabled:mdt-opacity-50' }),

  /* ── ICONS ───────────────────────────────────────────────────────── */
  T('color.icon', 'icon', 'A glyph beside text: the toolbar\'s slate glyph, a menu row\'s icon (it wears its label\'s ink).', '#516281', 'console neutral-90 (C-70, I-26)', '#8E9FBC', '--neutral-light dark · --chart-line-type-icon (both)', { lib: '--mdt-neutral-90', on: SURFACES }),
  T('color.icon.subtle', 'icon', 'A quiet glyph: the row-action ⋯ at rest, the search magnifier, the held lock.', '#8FA0BD', 'console --mdt-faint (K-Table-01, K-Field-03)', '#6A7FA0', '--neutral-regular dark', { lib: '--mdt-faint', on: SURFACES }),
  T('color.icon.brand', 'icon', 'The Name tile\'s glyph and the owner shield, in the interactive blue.', '#0262DE', 'console blue-60 (C-90, C-91)', '#008CFF', '--severity-maintenance dark · --page-link-color dark', { lib: '--mdt-blue-60', on: SURFACES }),
  T('color.icon.inverse', 'icon', 'A glyph on a bold fill: the primary button\'s icon, the checkbox tick, the switch\'s thumb.', '#FFFFFF', 'console --mdt-primary-foreground', '#0B1628', 'storybook neutral-160, with color.text.inverse (2026-09-24)', { lib: '--mdt-primary-foreground', on: ['color.background.brand.bold', 'color.background.selected.bold', 'color.background.neutral.bold'], note: 'The switch thumb on the off track: 1.5:1 in light today (white on #CAD3E2) and 2.6:1 in dark (#07101F on #485975) - a shape the track outlines, under the 3:1 floor on both sides; his call whether the dark thumb stays light (#CAD3E2, the sisters\' page text) instead.' }),

  /* ── SHADOWS ─────────────────────────────────────────────────────── */
  T('elevation.shadow.overlay', 'surface', 'The lg shadow under a menu, a popover, a date panel.', '0 10px 15px -3px rgba(0,0,0,.1), 0 4px 6px -4px rgba(0,0,0,.1)', 'console --mdt-shadow-lg (B-103)', '0 2px 8px rgba(0, 0, 0, 0.5)', '--tooltip-box-shadow dark · --shadow-feature-card dark 0 1px 2px rgba(0, 0, 0, 0.3), 0 4px 12px rgba(0, 0, 0, 0.4)', { lib: '--mdt-shadow-lg' }),
  T('elevation.shadow.raised', 'surface', 'A card\'s lift.', 'none', 'console: cards carry an edge and no shadow (C-54)', '0 1px 2px rgba(0, 0, 0, 0.3), 0 4px 12px rgba(0, 0, 0, 0.4)', '--shadow-feature-card dark (ServiceOps); --widget-box-shadow dark is #000', { lib: '--mdt-shadow-none', flag: 'Dark cards would gain a shadow light cards do not have. Keep none in dark too, or take the sisters\' lift. His call.' }),

  /* ── COMPONENT TOKENS (only where a part needs its own) ───────────── */
  T('component.nav.background', 'component', 'The left nav\'s ground.', '#F7FAFC', 'console: the nav renders neutral-10 (C-72)', '#0B1627', 'elevation.surface.sunken - Pranjal 2026-09-24: the light hierarchy holds in dark, the rail a step BELOW the content (was #172336, the raised step, which put it above)', { lib: 'LeftNav', flag: 'The ladder would put the nav on the canvas step (#0B1627); the sisters put it on the card step (#172336). His call.' }),
  T('component.nav.hovered', 'component', 'A nav row under the pointer.', '#ECF1F9', 'console neutral-20 (C-72)', '#1D2A3E', '--nav-hover-bg dark (both products)', { lib: 'LeftNav' }),
  T('component.nav.selected', 'component', 'The selected nav row - the one screen you are on. Light: the same fill as hover, as the console ships it; dark: the same as hover too, pending his call (2026-09-24: the console typed #ECF1F9 here and the map could not reach it - 1.08:1 under the dark ink).', '#ECF1F9', 'console sidebarNav.css line 51 (typed in; now --mdt-nav-selected)', '#1D2A3E', 'component.nav.hovered dark; his call pending', { lib: 'LeftNav' }),
  T('component.nav.text', 'component', 'A nav row\'s label and icon (at rest the console draws them at 72% of this; selected, full).', '#070F1D', 'console: the nav\'s ink is the near-black (C-72; rendered on /users)', '#CAD3E2', '--nav-text-color dark (both products)', { lib: 'LeftNav', on: ['component.nav.background'] }),
  T('component.tooltip.text', 'component', 'The tooltip\'s words.', '#FFFFFF', 'console: white on the inverse ground', '#CAD3E2', '--tooltip-text-color dark (both products)', { lib: 'Tooltip', on: ['color.background.inverse'] }),
  T('component.tooltip.divider', 'component', 'A hairline inside a tooltip.', 'rgba(255, 255, 255, 0.15)', 'carried from the sisters: --tooltip-divider-color (the console\'s tooltip draws no divider today)', 'rgba(255, 255, 255, 0.15)', '--tooltip-divider-color (ServiceOps; the same in both themes)', { lib: '-', note: 'Not a console value: the sisters\' job, carried so the family has it.' }),
  T('component.table.header.background', 'component', 'The table heading row.', '#FFFFFF', 'console: white headings separated by the underline (K-Table-05; rendered thead th)', '#172336', 'elevation.surface.raised dark - the heading wears the card, exactly as in light; the underline (color.border) separates it', { sisterLight: '#ECF1F9 --grid-header-bg (tinted; dark rgba(72,89,117,.4) - not followed)', lib: 'thead th', note: 'Light heading and rows share one ground, so dark does too. color.text.subtle on it measures above 4.5:1.' }),
  T('component.table.row.hovered', 'component', 'A table row under the pointer (rows sit on a card).', 'rgba(247, 250, 252, 0.5)', 'console: neutral-10 at half strength (K-Table-32, audit 2026-09-22)', '#1D2A3E', '--apm-heatmap-hover-color dark · --nav-hover-bg dark (one step up from the card)', { lib: 'table.css --tbl-hover' }),
  T('component.button.outline.border', 'component', 'The outline button\'s edge.', '#E3E8F2', 'console: the outline button and the toolbar square wear neutral-30 (C-70)', 'rgba(255, 255, 255, 0.8)', '--default-button-border dark (both products)', { lib: 'Button outline', flag: 'The sisters draw a bright 80% white edge in dark; color.border.bold (#2B394F) would be the quiet alternative.' }),
  T('component.checkbox.background', 'component', 'An unchecked checkbox\'s fill.', '#FFFFFF', 'console: white (K-Checkbox-03)', '#2B394F', '--checkbox-bg dark (both products)', { lib: 'Checkbox', note: 'The sisters fill an unchecked box; color.background.input would leave a hole.' }),
  T('component.radio.border', 'component', 'An unchosen radio\'s ring.', '#E3E8F2', 'console neutral-30 (the field edge)', '#204CA2', '--radio-btn-box-border-color dark = --focus-color (both products)', { lib: 'Radio', flag: 'The sisters\' dark radio ring is blue; color.border.bold (#2B394F) would match the checkbox instead.' }),
  T('component.code.background', 'component', 'A code chip\'s ground.', '#ECF1F9', 'console neutral-20 (Kbd / CodeWell)', '#172336', '--code-tag-background-color dark (both products)', { lib: 'Kbd / CodeWell' }),
  T('component.input.addon', 'component', 'A field\'s addon glyph or unit at rest.', '#8FA0BD', 'console --mdt-faint (the adornment glyph at rest, K-Field)', '#CAD3E2', '--input-addon-color dark (both products)', { lib: 'Input adornment', flag: 'The sisters brighten the addon to page text in dark; color.icon.subtle (#6A7FA0) would keep it quiet.' }),
];

/* Badge tones as pairs - the six tones the console paints (C-83/C-84) and their dark twins by the tinted-chip rule. */
const badges = [
  { tone: 'neutral', light: { fill: '#F7FAFC', ink: '#1D2B3E', dot: '#8FA0BD' }, dark: { fill: 'rgba(255, 255, 255, 0.08)', ink: '#8E9FBC', dot: '#6A7FA0' }, from: '--detail-tag-neutral-bg / -text dark · dot --neutral-regular dark' },
  { tone: 'slate', light: { fill: '#ECF1F9', ink: '#1D2B3E', dot: '#516281' }, dark: { fill: '#2B394F', ink: 'rgba(202, 211, 226, 0.8)', dot: '#8E9FBC' }, from: '--default-tag-bg / -text-color dark (ServiceOps; ObservOps\' bg disagrees) · dot --neutral-light dark' },
  { tone: 'success', light: { fill: '#DCF4E4', ink: '#21823A', dot: '#34A853' }, dark: { fill: 'rgba(16, 185, 129, 0.24)', ink: '#5ED6A8', dot: '#36D576' }, from: '--detail-tag-success-bg / -text dark · dot --severity-clear dark' },
  { tone: 'warning', light: { fill: '#FFF3DB', ink: '#9F6404', dot: '#FDB13F' }, dark: { fill: 'rgba(180, 105, 14, 0.26)', ink: '#E3A44A', dot: '#FAD100' }, from: '--detail-tag-warning-bg / -text dark · dot --severity-warning dark' },
  { tone: 'danger', light: { fill: '#FCE3E6', ink: '#B51225', dot: '#DD132B' }, dark: { fill: 'rgba(192, 57, 43, 0.24)', ink: '#F17A73', dot: '#EC5B5B' }, from: '--detail-tag-danger-bg dark · ink --secondary-red-light · dot --severity-critical' },
  { tone: 'information (info)', light: { fill: '#F0F6FE', ink: '#0262DE', dot: '#0262DE' }, dark: { fill: 'rgba(46, 111, 168, 0.26)', ink: '#7FB2E0', dot: '#008CFF' }, from: '--detail-tag-info-bg / -text dark · dot --severity-maintenance dark' },
  { tone: 'inverse', light: { fill: '#1D2B3E', ink: '#FFFFFF', dot: '#FFFFFF' }, dark: { fill: '#E3E8F2', ink: '#07101F', dot: '#07101F' }, from: 'the primary inversion (--primary dark, --primary-button-text dark)' },
];

/* Avatar tones: the console's six pairs (C-93 as the gallery renders them, blue as the console draws it). Dark by the
 * sisters' tinted-chip rule: the hue as a 24% wash with the ink lightened. The sisters themselves have ONE avatar pair
 * (ObservOps: #E0EBF5 / #1D2A3E → #172336 / #FFFFFF). Every dark hue and ink is a sister dark value. */
const avatars = [
  { tone: 'blue', light: { fill: '#F0F6FE', ink: '#0262DE' }, dark: { fill: 'rgba(0, 140, 255, 0.24)', ink: '#7FB2E0' }, from: 'hue --severity-maintenance dark · ink --detail-tag-info-text dark' },
  { tone: 'green', light: { fill: '#D4F2E3', ink: '#1B6540' }, dark: { fill: 'rgba(54, 213, 118, 0.24)', ink: '#5ED6A8' }, from: 'hue --severity-clear dark · ink --detail-tag-success-text dark' },
  { tone: 'amber', light: { fill: '#FFE3CC', ink: '#994200' }, dark: { fill: 'rgba(250, 153, 80, 0.24)', ink: '#E3A44A' }, from: 'hue --severity-major dark · ink --detail-tag-warning-text dark' },
  { tone: 'rose', light: { fill: '#FCE3E6', ink: '#B51225' }, dark: { fill: 'rgba(236, 91, 91, 0.24)', ink: '#F17A73' }, from: 'hue --severity-critical · ink --secondary-red-light (4.33:1 - a hair under)' },
  { tone: 'purple', light: { fill: '#F4EEFC', ink: '#6C2ED1' }, dark: { fill: 'rgba(168, 85, 247, 0.24)', ink: '#BB9AF7' }, from: 'hue --chart-neon-purple dark · ink --license-violet dark (ObservOps)' },
  { tone: 'slate', light: { fill: '#E4E9F1', ink: '#2B3950' }, dark: { fill: '#172336', ink: '#FFFFFF' }, from: '--avatar-initials-bg / -color dark (ObservOps)' },
];

/* The status ramp both sisters share (light → dark). The -lighter/-lightest/-darker steps carry one value; the
 * separate -dot-box step is not carried here. */
const status = [
  ['down', '#AD1111', '#F3C9C4', '#AD1111', '#1E0202'], ['critical', '#EC5B5B', '#FEF5F5', '#EC5B5B', '#310C0C'], ['major', '#F47C22', '#FDDCC4', '#FA9950', '#541914'],
  ['warning', '#E8B407', '#FFF1B3', '#FAD100', '#543308'], ['clear / up', '#14B053', '#D1FAE0', '#36D576', '#0D3A1F'], ['maintenance', '#006DFA', '#CCE4FF', '#008CFF', '#001489'],
  ['stop', '#E87587', '#FFDFE5', '#FF91A0', '#3E0614'], ['unreachable', '#6D2ED1', '#E7DCFA', '#8C5BD8', '#22094A'], ['disable', '#81929F', '#D9E3EA', '#99AAB7', '#0D151A'],
  ['unknown', '#B1B1B1', '#FCFCFC', '#B1B1B1', '#2E2E2E'], ['suspended (ServiceOps)', '#BE9669', '#FFEED7', '#D6B084', '#2D1B04'], ['suspended (ObservOps)', '#515C4B', '#E3E5E2', '#8A977F', '#20241D'], ['none', '#6FA8BB', '#DBF8FF', '#8AC1D3', '#04232C'],
].map(([name, light, lightTint, dark, darkTint]) => ({ name, light, lightTint, dark, darkTint }));

/* Chart colours, light → dark, straight from the sisters (both agree), plus the chart furniture. */
const chart = [
  ['vivid teal', '#0D9488', '#14B8A6'], ['tangerine', '#F97316', '#FB923C'], ['neon purple', '#9333EA', '#A855F7'], ['lime green', '#65A30D', '#84CC16'], ['hot pink', '#DB2777', '#EC4899'], ['aqua', '#0891B2', '#06B6D4'],
  ['golden yellow', '#CA8A04', '#EAB308'], ['electric coral', '#EF4444', '#FF6B6B'], ['emerald green', '#059669', '#10B981'], ['fuchsia', '#C026D3', '#D946EF'], ['amber', '#F59E0B', '#FBBF24'], ['indigo', '#7C3AED', '#8B5CF6'],
  ['sunset orange', '#EA580C', '#F97316'], ['mint green', '#14B8A6', '#2DD4BF'], ['rose red', '#E11D48', '#F43F5E'], ['chartreuse', '#84CC16', '#A3E635'], ['bright violet', '#A21CAF', '#C026D3'], ['vibrant magenta', '#DB2777', '#E83E8C'],
  ['grid line (--chart-grid-line-color)', 'rgba(236, 241, 249, 0.8)', 'rgba(23, 35, 54, 0.8)'], ['legend text (--chart-legend-color)', 'rgba(54, 70, 88, 0.9)', 'rgba(255, 255, 255, 0.8)'], ['empty slice (--chart-null-color; ServiceOps dark says #000)', '#E3E8F2', '#2B394F'],
].map(([name, light, dark]) => ({ name, light, dark }));

/* The shared neutral ramp: one column of hexes, three sets of names. "library comment" = the number the library's
 * globals.css comment gives that hex; the console's live value at that step can differ (C-09). */
const ramp = [
  ['#FFFFFF', 'white', '--page-background-color (light)'], ['#F7FAFC', 'console neutral-10 (renders a unit off the library\'s #F6F9FC)', 'not in the sisters (ServiceOps\' tile header is #F7F9FC)'], ['#F6F9FC', 'library comment: neutral-10', '--nav-panel-bg (light)'], ['#ECF1F9', 'neutral-20', '--neutral-lightest (light) · --list-menu-hover (light)'],
  ['#E3E8F2', 'neutral-30', '--neutral-lighter · --border-color (light) · --primary (dark)'], ['#CAD3E2', 'neutral-40', '--primary-alt (dark) · --page-text-color (dark)'], ['#8E9FBC', 'library comment: neutral-50', '--neutral-light (dark) · --tabs-text-color (dark)'], ['#8FA0BD', 'console neutral-50 and neutral-70 · --mdt-faint', 'not in the sisters (one unit off #8E9FBC)'],
  ['#7186A8', 'library comment: neutral-60', '--neutral-regular (light)'], ['#6A7FA0', '(the library comment\'s neutral-70 is #697FA0)', '--neutral-light (light) · --neutral-regular (dark)'], ['#516281', 'neutral-90', '(--tabs-text-color light is #516381, one unit off)'], ['#485975', 'library comment: neutral-100', '--slider-tracker · --loader-primary-color (dark)'],
  ['#2B394F', 'library comment: neutral-110', '--neutral-dark (light) · --field-border-color (dark)'], ['#1D2B3E', 'console neutral-110, 130 and 150 (one hex, three names)', '(--page-text-color light is #1D2A3E, one unit off)'], ['#1D2A3E', 'library comment: neutral-130', '--primary-alt (light) · --border-color (dark) · --dropdown-background (dark)'], ['#172336', 'neutral-140', '--neutral-darker · --nav-panel-bg (dark) · --widget-background-color (dark)'],
  ['#111C2C', 'library comment: neutral-150', '--primary (ObservOps light) · --input-background-disabled (dark)'], ['#0B1627', '(the library comment\'s neutral-160 is #0B1628)', '--dashboard-background (dark)'], ['#070F1D', 'console neutral-160 · --mdt-black', 'not in the sisters (one unit off #07101F)'], ['#07101F', '—', '--primary (ServiceOps light) · --page-background-color (dark)'],
];

/* Where the library's existing semantic tokens land. */
const migration = [
  ['--mdt-background', 'elevation.surface'], ['--mdt-card / --mdt-surface-raised', 'elevation.surface.raised'], ['--mdt-popover', 'elevation.surface.overlay'], ['--mdt-foreground', 'color.text.brand (it is the near-black; reading text is color.text)'],
  ['--mdt-muted', 'color.background.neutral.subtle'], ['--mdt-secondary', 'elevation.surface.sunken (Pranjal 2026-09-25: the Users drawer contact card colour is the secondary, both themes; was color.background.neutral)'], ['--mdt-muted-foreground', 'color.text.subtlest (the console already re-points it to #8FA0BD; the library\'s own value is still ink-500 #727283)'], ['--mdt-faint', 'color.text.subtlest'],
  ['--mdt-border', 'color.border'], ['--mdt-input', 'color.border.input'], ['--mdt-ring', 'color.border.focused'], ['--mdt-primary', 'color.background.brand.bold · color.text.brand · color.background.selected.bold (controls)'], ['--mdt-primary-foreground', 'color.text.inverse · color.icon.inverse'],
  ['--mdt-destructive', 'color.text.danger · color.background.danger.bold · color.border.danger'], ['--mdt-success / --mdt-warning / --mdt-info', 'color.text.<tone> for inks; the bold fills only where a solid button exists'],
  ['--mdt-feedback-<tone>-bg / -border / -icon', 'color.background.<tone> · color.border.<tone> · color.text.<tone>'], ['--mdt-accent', 'color.background.selected'], ['Badge tone pairs (raw in Badge.tsx)', 'the badge pairs table'], ['Avatar tone pairs', 'the avatar pairs table'],
];

module.exports = { semantic, badges, avatars, status, chart, ramp, migration };
