#!/usr/bin/env node
/* THE PUBLIC API RATCHET - a name this package has published never disappears
 * by accident.
 *
 * WHY THIS EXISTS. 1.0.0 published `OPERATORS`, `isGroup`, `isComplete`,
 * `liveItems` and `matchRow`. The console imported the qualified forms -
 * `ADVANCED_FILTER_OPERATORS`, `isFilterGroup` and the rest - which a pull
 * request had carried and a fold of that pull request did not keep. Nothing
 * said so. Lint passed, 3,600 tests passed, the build passed, the package
 * published, and the first anyone knew was every table with More filters
 * failing to load in the console (2026-10-09).
 *
 * That class of break is mechanical, so it should be caught mechanically.
 *
 * HOW IT WORKS. `scripts/api-baseline.json` holds every name the package
 * exports. The check rebuilds that list from `dist/` and fails if anything in
 * the baseline is gone. Added names are free; the ratchet only turns one way.
 *
 *     npm run check:api                 compare dist/ against the baseline
 *     node scripts/check-api.mjs --record --reason "..."    move the baseline
 *
 * WHY A BASELINE FILE AND NOT A LOOKUP AGAINST npm. A gate that needs the
 * network fails when the network does, and a gate that fails for reasons
 * unrelated to the change is one people learn to route around - the same
 * reasoning `check:tokens` and the colour gate already follow here. The
 * baseline is also reviewable: a removal shows up as a line in the diff, which
 * a live lookup never would.
 *
 * WHAT IT READS. Two sources, because neither is complete on its own: the
 * `export declare` lines in `dist/index.d.ts` (types and values, 940 of them
 * today) and the runtime keys of `dist/index.cjs` (419, twelve of which never
 * appear in the declarations). The union is the surface a consumer can reach.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const BASELINE = join(here, 'api-baseline.json');
const require_ = createRequire(import.meta.url);

const DECLARED =
  /^export\s+declare\s+(?:abstract\s+)?(?:function|interface|type|const|let|var|class|enum|namespace)\s+([A-Za-z_$][\w$]*)/gm;

/** Every name a consumer can import from the package root, from both sources. */
function readApi() {
  const dts = join(root, 'dist/index.d.ts');
  const cjs = join(root, 'dist/index.cjs');
  if (!existsSync(dts) || !existsSync(cjs)) {
    console.error('check:api needs a build first - run `npm run build`.');
    process.exit(2);
  }
  const names = new Set();
  for (const [, name] of readFileSync(dts, 'utf8').matchAll(DECLARED)) names.add(name);
  for (const name of Object.keys(require_(cjs))) names.add(name);
  names.delete('default');
  return [...names].sort();
}

const current = readApi();
const args = process.argv.slice(2);
const record = args.includes('--record');
const reasonAt = args.indexOf('--reason');
const reason = reasonAt === -1 ? '' : (args[reasonAt + 1] ?? '');

const prior = existsSync(BASELINE) ? JSON.parse(readFileSync(BASELINE, 'utf8')) : null;
const removed = prior ? prior.names.filter((n) => !current.includes(n)) : [];
const added = prior ? current.filter((n) => !prior.names.includes(n)) : current;

if (record) {
  // A removal is sometimes right - a deprecated family finally going. It is
  // never right by accident, so it has to be said out loud and is kept in the
  // file, the way the colour gate keeps its reasons.
  if (removed.length && !reason) {
    console.error(
      `Refusing to record: ${String(removed.length)} name(s) would be dropped from the public API.\n` +
        `  ${removed.slice(0, 12).join(', ')}${removed.length > 12 ? ', …' : ''}\n\n` +
        'If that is deliberate, say why:\n' +
        '  node scripts/check-api.mjs --record --reason "TableOld retired in 3.0.0"\n'
    );
    process.exit(1);
  }
  const reasons = prior?.reasons ?? {};
  if (reason) reasons[new Date().toISOString().slice(0, 10)] = reason;
  writeFileSync(
    BASELINE,
    `${JSON.stringify({ note: 'Every name the package exports. Generated by scripts/check-api.mjs --record. A name here must not disappear without a reason.', recorded: new Date().toISOString().slice(0, 10), reasons, count: current.length, names: current }, null, 2)}\n`
  );
  console.log(
    `Recorded ${String(current.length)} public names` +
      (added.length ? `, ${String(added.length)} new` : '') +
      (removed.length ? `, ${String(removed.length)} dropped: ${reason}` : '') +
      '.'
  );
  process.exit(0);
}

if (!prior) {
  console.error('No baseline yet. Create it with:\n  node scripts/check-api.mjs --record\n');
  process.exit(1);
}

if (removed.length) {
  console.error(
    `\n  ${String(removed.length)} name(s) this package has published are gone from the build:\n\n` +
      removed.map((n) => `    ${n}`).join('\n') +
      '\n\n' +
      '  Every one of these is an import that stops working in somebody else\'s\n' +
      '  project, with no warning until it runs. If a name moved, export the old\n' +
      '  one beside the new one - both cost nothing. If it genuinely goes:\n\n' +
      '    node scripts/check-api.mjs --record --reason "why"\n'
  );
  process.exit(1);
}

console.log(
  `public API ok  ${String(current.length)} names, none dropped` +
    (added.length ? `, ${String(added.length)} new` : '') +
    ` (baseline ${String(prior.recorded)})`
);
