#!/usr/bin/env node
/* THE DARK THEME, GENERATED FROM THE COLOUR MAP - the library's own block (2026-09-26).
 *
 * Pranjal, 2026-09-25/26: "We will continue with the dark theme implementation on component of storybook." The map
 * (scripts/dark-theme/tokens.cjs, his finalised tokens of 2026-09-24, home here in the design system from today) was
 * first applied in the console (next-gen-ui/scripts/theme-dark.cjs → src/styles/theme-dark.css). This is the same
 * method pointed at the library's own light palette, so the storybook and the console read ONE dark theme.
 *
 *   node scripts/theme-dark.cjs          rewrites the generated block in src/styles/globals.css
 *   node scripts/theme-dark.cjs --check  exits 1 if the block on disk is not what the map says (CI / pre-commit)
 *
 * What it does, per colour variable the library's :root declares:
 *   1. the explicit map below - the map's semantic token for that job (the console's table, less the console-only
 *      entries: the library's --mdt-white stays white and --mdt-black stays black);
 *   2. otherwise a colour ramp step gets the tinted-chip rule (a tint = the hue's mid step at a quarter over the dark
 *      raised surface; an ink = a lighter step of the same hue);
 *   3. otherwise the variable keeps its light value (radius, fonts, shadows, z-index, the AI gradient stops).
 * Every declaration the previous dark block carried that the map does not cover is carried over verbatim and listed,
 * so nothing disappears in silence.
 *
 * THE SWITCH is <html data-theme="dark"> - the console's. The storybook sets it too (.storybook/preview.ts), beside
 * the `.dark` class it still needs for the `dark:` variants that are being retired family by family. When the last
 * `dark:` variant goes, the class goes with it and there is one switch. */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const CSS = path.join(ROOT, 'src', 'styles', 'globals.css');
const model = require('./dark-theme/tokens.cjs');
const SELECTOR = "[data-theme='dark']";
const BEGIN = '  /* ── THE DARK THEME · GENERATED BY scripts/theme-dark.cjs FROM scripts/dark-theme/tokens.cjs · DO NOT EDIT BY HAND ── */';
const END = '  /* ── END OF THE GENERATED DARK THEME ── */';

/* ── colour maths ── */
const hexToRgb = (h) => { const s = h.replace('#', ''); const n = parseInt(s.length === 3 ? s.split('').map((c) => c + c).join('') : s, 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255]; };
const rgbToHex = ([r, g, b]) => '#' + [r, g, b].map((v) => Math.round(Math.max(0, Math.min(255, v))).toString(16).padStart(2, '0')).join('').toUpperCase();
const parseRgba = (s) => { const m = s.match(/rgba?\(\s*(\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/); return m ? [Number(m[1]), Number(m[2]), Number(m[3]), m[4] === undefined ? 1 : Number(m[4])] : null; };
const over = (fg, alpha, bgHex) => { const b = hexToRgb(bgHex); return rgbToHex(fg.map((c, i) => c * alpha + b[i] * (1 - alpha))); };
const SURFACE = '#172336'; // the raised surface a tint sits on in dark
const solid = (v) => { if (!v) return null; if (v.startsWith('#')) return v.toUpperCase(); const a = parseRgba(v); if (!a) return null; return a[3] >= 1 ? rgbToHex(a) : over(a, a[3], SURFACE); };
/* numbers the way prettier prints them (no trailing zeros), so `prettier --write` leaves the block as generated */
const num = (n) => n.toFixed(2).replace(/\.?0+$/, '');
const hexToHsl = (hex) => { let [r, g, b] = hexToRgb(hex).map((v) => v / 255); const max = Math.max(r, g, b), min = Math.min(r, g, b); let h = 0, s = 0; const l = (max + min) / 2; if (max !== min) { const d = max - min; s = l > 0.5 ? d / (2 - max - min) : d / (max + min); switch (max) { case r: h = (g - b) / d + (g < b ? 6 : 0); break; case g: h = (b - r) / d + 2; break; default: h = (r - g) / d + 4; } h /= 6; } return `${num(h * 360)} ${num(s * 100)}% ${num(l * 100)}%`; };
const hslToHex = (triple) => { const m = triple.trim().match(/^([\d.]+)\s+([\d.]+)%\s+([\d.]+)%$/); if (!m) return null; const h = Number(m[1]) / 360, s = Number(m[2]) / 100, l = Number(m[3]) / 100; const f = (n) => { const k = (n + h * 12) % 12; const a = s * Math.min(l, 1 - l); return l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1)); }; return rgbToHex([f(0) * 255, f(8) * 255, f(4) * 255]); };

/* ── the library's light palette: every --mdt-* declaration in :root, resolved to a hex where it is a colour ── */
const css = fs.readFileSync(CSS, 'utf8');
const eol = css.includes('\r\n') ? '\r\n' : '\n';
function blockAt(text, startIdx) {
  /* from the first "{" at/after startIdx to its matching "}" */
  const open = text.indexOf('{', startIdx); let depth = 0;
  for (let i = open; i < text.length; i++) { if (text[i] === '{') depth++; else if (text[i] === '}') { depth--; if (depth === 0) return { open, close: i }; } }
  throw new Error('unbalanced block');
}
const rootIdx = css.search(/^\s*:root\s*{/m);
const root = blockAt(css, rootIdx);
const rootBody = css.slice(root.open + 1, root.close);
const declRe = /--mdt-([a-z0-9-]+)\s*:\s*([^;]+);/g;
/* a value as one line: comments out, one space, `var( x )` closed up (the file breaks long ones across lines) */
const tidy = (v) => v.replace(/\/\*[^]*?\*\//g, '').replace(/\s+/g, ' ').replace(/var\(\s+/g, 'var(').replace(/\s+\)/g, ')').trim();
const light = {}; const order = [];
for (const m of rootBody.matchAll(declRe)) { const key = m[1]; if (!(key in light)) order.push(key); light[key] = tidy(m[2]); }
const hexOf = (key, seen = new Set()) => {
  const v = light[key]; if (v == null || seen.has(key)) return null; seen.add(key);
  if (/^[\d.]+ [\d.]+% [\d.]+%$/.test(v)) return hslToHex(v);
  const ref = v.match(/^var\(--mdt-([a-z0-9-]+)\)$/); if (ref) return hexOf(ref[1], seen);
  return null;
};
const P = {}; for (const key of order) { const hex = hexOf(key); if (hex) P[key] = hex; }

/* ── the map: variable → dark hex, by job ── */
const S = Object.fromEntries(model.semantic.map((t) => [t.name, t]));
const D = (name) => (S[name] ? solid(S[name].dark) : null);
const explicit = {
  background: D('elevation.surface'),
  /* CARDS ARE FLAT (Pranjal, 2026-09-24): the card token is the page surface in dark too, the edge does the work; the
   * raised step stays for what really lifts */
  card: D('elevation.surface'), 'surface-raised': D('elevation.surface.raised'), popover: D('elevation.surface.overlay'),
  foreground: D('color.text.brand'), 'card-foreground': D('color.text.brand'), 'popover-foreground': D('color.text.brand'), 'secondary-foreground': D('color.text.brand'),
  /* black stays black (the scrim reads it); white stays white (a real colour, not the console's paper) */
  black: '#000000', white: '#FFFFFF', 'neutral-160': D('color.text.brand'),
  muted: D('color.background.neutral.subtle'), secondary: D('elevation.surface.sunken') /* Pranjal 2026-09-25: the secondary is the contact card's colour, both themes */,
  'muted-foreground': D('color.text.subtlest'), 'muted-foreground-subtle': D('color.text.subtlest'), faint: D('color.text.subtlest'), 'neutral-50': D('color.text.subtlest'), 'neutral-70': D('color.text.subtlest'),
  'ink-400': D('color.text.subtlest'), 'ink-500': D('color.text.subtle'),
  border: D('color.border'), 'feedback-neutral-border': D('color.border'), input: D('color.border.input'), ring: D('color.border.focused'),
  /* the primary button = the storybook's neutral-20 in dark, through three tokens (Pranjal, 2026-09-24 night) */
  primary: D('color.background.brand.bold'), 'primary-hover': D('color.background.brand.bold.hovered'), 'primary-active': D('color.background.brand.bold.pressed'), 'primary-foreground': D('color.text.inverse'), 'primary-foreground-muted': '#485975', 'primary-foreground-subtle': '#6A7FA0',
  'destructive-foreground': D('color.text.inverse'), 'info-foreground': D('color.text.inverse'), 'success-foreground': D('color.text.inverse'), 'warning-foreground': D('color.text.inverse'),
  'neutral-10': D('elevation.surface.sunken'), 'neutral-20': D('color.border') /* the hairline; in dark the same hex as the quiet fill */, 'neutral-30': D('color.border.bold'), 'neutral-40': D('color.background.neutral.bold'),
  'neutral-60': '#7186A8', 'neutral-80': D('color.text.subtle'), 'neutral-90': D('color.text.subtle'), 'neutral-100': D('color.text.subtle'),
  'neutral-110': D('color.text'), 'neutral-120': D('color.text'), 'neutral-130': D('color.text'), 'neutral-150': D('color.text'), 'neutral-140': D('color.text.brand'),
  'feedback-text': D('color.text'), 'feedback-title': D('color.text'),
  'azure-60': D('color.link'), 'blue-60': D('color.link'), info: D('color.link'), 'feedback-info-icon': D('color.text.information'), 'accent-foreground': D('color.link'), 'blue-50': D('color.link'),
  accent: D('color.background.information'), 'feedback-info-bg': D('color.background.information'), 'blue-10': D('color.background.information'), 'blue-05': D('color.background.information'),
  'feedback-info-border': over([46, 111, 168], 0.45, SURFACE), 'blue-20': over([46, 111, 168], 0.45, SURFACE),
  destructive: D('color.text.danger'), 'red-60': D('color.text.danger'), 'red-70': '#F17A73', 'feedback-danger-icon': '#F17A73', 'red-65': D('color.background.danger.bold.hovered'),
  'feedback-danger-bg': D('color.background.danger'), 'red-10': D('color.background.danger'), 'red-05': D('color.background.danger'), 'feedback-danger-border': over([192, 57, 43], 0.45, SURFACE), 'red-20': over([192, 57, 43], 0.45, SURFACE),
  success: '#36D576', 'green-60': '#36D576', 'emerald-60': '#36D576', 'green-80': D('color.text.success'), 'feedback-success-icon': D('color.text.success'), 'green-70': D('color.text.success'),
  'feedback-success-bg': D('color.background.success'), 'green-10': D('color.background.success'), 'green-05': D('color.background.success'), 'feedback-success-border': over([16, 185, 129], 0.45, SURFACE), 'green-20': over([16, 185, 129], 0.45, SURFACE),
  warning: '#FAD100', 'orange-60': '#FAD100', 'orange-80': D('color.text.warning'), 'feedback-warning-icon': D('color.text.warning'), 'orange-70': D('color.text.warning'),
  'feedback-warning-bg': D('color.background.warning'), 'orange-10': D('color.background.warning'), 'orange-05': D('color.background.warning'), 'feedback-warning-border': over([180, 105, 14], 0.45, SURFACE), 'orange-20': over([250, 153, 80], 0.24, SURFACE),
  'orange-90': D('color.text.warning'),
  'feedback-ai-bg': D('color.background.ai'), 'purple-10': D('color.background.ai'), 'purple-05': D('color.background.ai'), 'feedback-ai-icon': D('color.text.ai'), 'purple-60': D('color.text.ai'), 'feedback-ai-border': over([168, 85, 247], 0.35, SURFACE),
  'feedback-neutral-bg': over([255, 255, 255], 0.08, SURFACE), 'feedback-neutral-icon': D('color.text.subtlest'),
  /* the left nav's own tokens (2026-09-24): the rail reads these and nothing else */
  'nav-background': D('component.nav.background'), 'nav-hover': D('component.nav.hovered'), 'nav-selected': D('component.nav.selected') || D('component.nav.hovered'), 'nav-text': D('component.nav.text'),
  'nav-label': D('color.text.subtle'), 'nav-line': D('color.border.bold') /* Pranjal 2026-09-25: neutral-140 - the plain border equals the overlay in dark */, 'nav-well': D('color.background.neutral'), 'nav-soon-bg': D('color.background.neutral'), 'nav-danger': D('color.text.danger'), 'nav-door-bg': over([46, 111, 168], 0.26, SURFACE),
};
/* the other colour ramps (cyan, teal, lime, magenta, yellow, indigo, and the deep steps): the tinted-chip rule */
const ramps = {};
for (const key of Object.keys(P)) { const m = key.match(/^([a-z]+)-(\d+)$/); if (m) (ramps[m[1]] = ramps[m[1]] || {})[Number(m[2])] = P[key]; }
const generic = (hue, step) => {
  const r = ramps[hue]; if (!r) return null;
  const mid = r[50] || r[60] || r[40]; if (!mid) return null;
  if (step <= 30) return over(hexToRgb(mid), 0.24, SURFACE);
  if (step <= 50) return r[40] || mid;
  if (step <= 70) return r[30] || r[40] || mid;
  return r[20] || r[30] || mid;
};
const dark = {}; const byRule = { model: 0, ramp: 0, kept: [] };
for (const key of order) {
  if (!P[key]) continue; /* not a colour: radius, fonts, shadows, z-index, alphas, gradient stops */
  if (explicit[key]) { dark[key] = explicit[key]; byRule.model++; continue; }
  const m = key.match(/^([a-z]+)-(\d+)$/);
  const g = m ? generic(m[1], Number(m[2])) : null;
  if (g) { dark[key] = g; byRule.ramp++; } else byRule.kept.push(key);
}
/* the six avatar tones (the organisation tiles): the map's avatar tier, fills composited on the raised surface */
for (const a of model.avatars) { const fill = solid(a.dark.fill), ink = solid(a.dark.ink); if (fill) { dark['avatar-' + a.tone + '-fill'] = fill; byRule.model++; } if (ink) { dark['avatar-' + a.tone + '-ink'] = ink; byRule.model++; } }
/* the nav's resting ink alpha is a token too (light 0.72, dark 0.84) */
const extras = { 'nav-rest-alpha': '0.84' };
/* what really keeps its light value: a colour variable nothing above gave a dark value to */
byRule.kept = byRule.kept.filter((k) => !(k in dark));

/* ── what the previous dark block carried that the map does not: carried over verbatim, and listed ── */
function previousBlock() {
  const b = css.indexOf(BEGIN), e = css.indexOf(END);
  if (b >= 0 && e > b) return { start: b, end: e + END.length, body: css.slice(b, e), generated: true };
  const m = css.search(/^\s*\.dark\s*{/m); if (m < 0) throw new Error('neither a generated block nor a .dark block in globals.css');
  const lineStart = css.lastIndexOf('\n', m) + 1; const blk = blockAt(css, m);
  return { start: lineStart, end: blk.close + 1, body: css.slice(blk.open + 1, blk.close), generated: false };
}
const prev = previousBlock();
const carried = [];
if (!prev.generated) {
  for (const m of prev.body.matchAll(declRe)) { const key = m[1]; if (!(key in dark) && !(key in extras)) carried.push([key, tidy(m[2])]); }
} else {
  const cm = prev.body.match(/\/\* carried over from the hand-written block[^]*?\*\/\s*([^]*?)\n\s*color-scheme/);
  if (cm) for (const m of cm[1].matchAll(declRe)) { const key = m[1]; if (!(key in dark) && !(key in extras)) carried.push([key, tidy(m[2])]); }
}

/* ── the block ── */
const toneClass = (t) => ({ 'information (info)': 'info' }[t.tone] || t.tone.replace(/ .*$/, ''));
function render() {
  const L = [];
  L.push(BEGIN);
  L.push(`  /* ${Object.keys(dark).length} colour variables from the map (${byRule.model} by the semantic token for the job, ${byRule.ramp} by the tinted-chip rule for a ramp step);`);
  L.push(`     ${byRule.kept.length} colour variables keep their light value (${byRule.kept.join(', ') || 'none'}); the rest of :root is not colour. */`);
  L.push(`  ${SELECTOR} {`);
  for (const [k, v] of Object.entries(dark)) L.push(`    --mdt-${k}: ${hexToHsl(v)}; /* ${v} */`);
  for (const [k, v] of Object.entries(extras)) L.push(`    --mdt-${k}: ${v};`);
  if (carried.length) {
    L.push('    /* carried over from the hand-written block - the map has no word on these yet */');
    for (const [k, v] of carried) L.push(`    --mdt-${k}: ${v};`);
  }
  L.push('    color-scheme: dark;');
  L.push('  }');
  L.push('  /* the badge tier by tone: badge.css sets --bdg-fill / --bdg-ink / --bdg-dot per tone class in light; the map\'s dark tier lands the same way */');
  for (const t of model.badges) {
    L.push(`  ${SELECTOR} .bdg-${toneClass(t)} {`);
    L.push(`    --bdg-fill: ${solid(t.dark.fill).toLowerCase()};`);
    L.push(`    --bdg-ink: ${solid(t.dark.ink).toLowerCase()};`);
    L.push(`    --bdg-dot: ${solid(t.dark.dot).toLowerCase()};`);
    L.push('  }');
  }
  L.push(END);
  return L.join(eol);
}
const block = render();
const next = css.slice(0, prev.start) + block + css.slice(prev.end);

/* prettier re-wraps the long shadow values after the write, so the comparison ignores whitespace */
const norm = (s) => s.replace(/\s+/g, ' ').trim();
if (process.argv.includes('--check')) {
  if (norm(next) !== norm(css)) { console.error('theme-dark: src/styles/globals.css is behind the map - run node scripts/theme-dark.cjs'); process.exit(1); }
  console.log('theme-dark: the dark block matches the map'); process.exit(0);
}
if (require.main === module) {
  fs.writeFileSync(CSS, next);
  /* the repo formats css on commit; formatting here keeps the working file identical to what a commit would hold */
  try { require('child_process').execSync('npx prettier --write src/styles/globals.css', { cwd: ROOT, stdio: 'ignore' }); } catch (e) { console.warn('theme-dark: prettier did not run (' + e.message + ')'); }
  console.log(`wrote the dark block into src/styles/globals.css: ${Object.keys(dark).length} variables (${byRule.model} by the map, ${byRule.ramp} by the ramp rule, ${byRule.kept.length} kept light: ${byRule.kept.join(', ') || 'none'}), ${model.badges.length} badge tones` + (carried.length ? `; carried over ${carried.length}: ${carried.map(([k]) => k).join(', ')}` : '') + (prev.generated ? '' : ' - replaced the hand-written .dark block'));
}
module.exports = { P, light, S, model, explicit, dark, byRule, extras, carried, SELECTOR, solid, over, hexToHsl, hexToRgb, rgbToHex, hslToHex, SURFACE, generic, render };
